### ISSUE TITLE
Stuff from one playthrough of Celicath

### ISSUE THREAD

**Issue by DioBal** [DioBal/TheGartic#102]
Credit to @Celicath 
"Played once, only commenting on bugs and inconsistencies

Cards
- Feather Guard targets enemy.
- Dynamic Entry: Has [MISSING_TITLE] and [MISSING_DESCRIPTION]
- Different from the sheet
  - God's Blood HP loss: 1x3 instead of 9
  - Polarity Disorder's Damage: 8 instead of 7
  - Pandamonium: No Weak or Vulnerable
  - Garbage Golem does not Exhaust.
  - Delayed Death has Ethereal.
  - Clear Intention does not Exhaust.
  - Supplicate to Inari costs 3 instead of 2
  - Wrong Rarities/Types
    - Heavy Slam is Common. (should be Uncommon)
    - Sparks is an Attack. (should be a Skill)
    - Suplicate to Inari is a Power. (Should be a Skill?)
- No Upgrades
  - Celestial Crafting, Hover
- Wordings
  - Supplicate to Inari should have tooltip for what Three-tailed Fox does.
  - Sheet of Paper needs previews
  - Elder's Knowledge: Wisdom should be a keyword
  - Pounce and Retreat, Void Defend, etc: Should have tooltip for what (Block Symbol) means.
  - Freefall needs Unplayable.
  - Arcane Toolbox should have Innate on top of the description.
  - Mischievous Fox, Fetching Fox: The summon's name in the Description needs a space.
  - Carry On, Little Shield Dude: Should use !M! to make it green when you preview their upgrades.
  - Scorpion Sting, Quick Cast: Needs a period at the end of the description.
  - Collect Self: stance should be Stance.
  - Garbage Golem: block should be Block.
- Other inconsistencies
  - Charge Beam is an Attack while Sparks is a Skill (although Sparks is 'incorrectly' implemented as an Attack)

Summons
- Mirrored Fox: Tooltip says 'gain 1 Block.'
- Fire Imp: Tooltip says 'deal 0 damage' 
- Approach's double damage buff affects all summons affected by attack modifiers, and they do not remove double damage buff.

- Inconsistencies on whether attack modifiers affect summons:
  - Mirrored Fox is unaffected by attack modifiers.
  - Dire Wolf is affected by attack modifiers. It says in the description
  - Fire Imp is affected by attack modifiers, even though it doesn't say that in the description.
  - Fire Imp is affected by Thorns, while Dire Wolf is not.
  - Fire Imp's damage is sometimes not correctly affected by attack modifiers right after it is summoned.

Power
- Flight Power from Soaring Form and Feather Guard are different. When you have both of them, you take 1/4 damage.
- Flight Power from Soaring Form is removed, it crashes with:
java.lang.ClassCastException: theGartic.TheGartic cannot be cast to com.megacrit.cardcrawl.monsters.AbstractMonster
	at com.megacrit.cardcrawl.powers.FlightPower.onRemove(FlightPower.java:74)
	at com.megacrit.cardcrawl.actions.common.RemoveSpecificPowerAction.update(RemoveSpecificPowerAction.java:53)
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:179)
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:325)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2532)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:876)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:423)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

Other
- If you try to load a save file created without this mod, it crashes."

**Comment by DioBal** [comment]
Er, edited by Bryan fixes:
"Cards
- No Upgrades for Celestial Crafting, Hover
  - But They have no upgrades listed on the sheet
- Feather Guard targets enemy.
- Dynamic Entry: Has [MISSING_TITLE] and [MISSING_DESCRIPTION]
- Different from the sheet
  - Supplicate to Inari costs 3 instead of 2
  - Wrong Rarities/Types
    - Heavy Slam is Common. (should be Uncommon)
    - Sparks is an Attack. (should be a Skill)
    - Suplicate to Inari is a Power. (Should be a Skill?)
- Wordings
  - Supplicate to Inari should have tooltip for what Three-tailed Fox does.
  - Sheet of Paper needs previews
  - Elder's Knowledge: Wisdom should be a keyword
  - Pounce and Retreat, Void Defend, etc: Should have tooltip for what (Block Symbol) means.
  - Arcane Toolbox should have Innate on top of the description.
  - Mischievous Fox, Fetching Fox: The summon's name in the Description needs a space.
  - Carry On, Little Shield Dude: Should use !M! to make it green when you preview their upgrades.
  - Scorpion Sting, Quick Cast: Needs a period at the end of the description.
- Other inconsistencies
  - Charge Beam is an Attack while Sparks is a Skill (although Sparks is 'incorrectly' implemented as an Attack)

Summons
- Mirrored Fox: Tooltip says 'gain 1 Block.'
- Fire Imp: Tooltip says 'deal 0 damage' 
- Approach's double damage buff affects all summons affected by attack modifiers, and they do not remove double damage buff.

- Inconsistencies on whether attack modifiers affect summons:
  - Mirrored Fox is unaffected by attack modifiers.
  - Dire Wolf is affected by attack modifiers. It says in the description
  - Fire Imp is affected by attack modifiers, even though it doesn't say that in the description.
  - Fire Imp is affected by Thorns, while Dire Wolf is not.
  - Fire Imp's damage is sometimes not correctly affected by attack modifiers right after it is summoned.

Other
- If you try to load a save file created without this mod, it crashes.
  - I can't recreate this - Bryan

Working
- Delayed Death is supposed to have ethereal
- Soaring Form now uses PlayerFlightPower instead of FlightPower
- God's blood 9 hp loss, not 1x3
- Polarity Disorder's Damage: 7 damage instead of 8
- Garbage Golem exhausts, and also has correct capitalization for Block
- Clear Intention exhausts
- Freeform now says unplayable
- Collect Self capitalizes Stance
- Pandamonium: Now talks about status effect in card description"
